Feature/#123 show files are generated
icapps/flutter-model-generator pull request #125
Opened 2022-12-20 21:19 UTC by ikbendewilliam

Fixed #123

2022-12-20 21:21 UTC, NicolaVerbeeck approved these changes

2022-12-21 07:33 UTC, vanlooverenkoen requested changes

2022-12-21 07:33 UTC, vanlooverenkoen commented on lib/writer/enum_model_writer.dart
> +      ..writeln("// GENERATED CODE - DO NOT MODIFY BY HAND")
move this generated text to a const somewhere so we don't need to update it in both files if we want to change this

2022-12-27 08:24 UTC, vanlooverenkoen approved these changes

2022-12-27 09:00 UTC, merged