Fix enum map and extension
icapps/flutter-model-generator pull request #133
Opened 2023-03-07 21:21 UTC by luca-vz

2023-03-07 21:29 UTC, ikbendewilliam commented
Next time add an issue with the details of what went wrong

2023-03-07 21:31 UTC, ikbendewilliam commented
LGTM
Sidenote, create a new issue for the deprecated lint rule and `ignore` field
```
   info • 'invariant_booleans' is a deprecated lint rule and should not be used
          • example/analysis_options.yaml:58:7 • deprecated_lint_hint
   info • 'ignore' is deprecated and shouldn't be used. Use `includeFromJson`
          and `includeToJson` with a value of `false` instead •
          example/lib/model/user/testing.dart:13:55 • deprecated_member_use
```

2023-03-08 09:59 UTC, vanlooverenkoen requested changes

2023-03-08 09:59 UTC, vanlooverenkoen commented on lib/util/case_util.dart
> +  String get upperCamelCase => _getUpperCamelCase();
There is no such thing as upperCamelCase. This is just PascalCase

2023-03-08 10:55 UTC, vanlooverenkoen commented
Ticket created for the ignore: https://github.com/icapps/flutter-model-generator/issues/134

2023-03-08 10:58 UTC, merged